version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
        - ./:/var/www
        - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini    
    networks:
      - lumen

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8084:80"
      - "444:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/      
    networks:
      - lumen

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: wishlistapi
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: wishlist
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: C6sR2<8&Z{pQ
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - lumen

#Docker Networks
networks:
  lumen:
    driver: bridge

#Volumes
volumes:
    dbdata:
      driver: local